name: "publish npm"

on: push

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v3
            - name: Setup Node 18
              uses: actions/setup-node@v18
              with:
                  node-version: 18
                  registry-url: https://registry.npmjs.org
            - name: Setup pnpm
              uses: pnpm/action-setup@v8.6.1
              with:
                  version: 8.6.1
            - name: build
              run: pnpm install && pnpm build
            - name: publish
              run: npm publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
